---
openapi: 3.0.3
info:
  description: |
    Sauce Labs Hosted Test Executor REST API.
  termsOfService: https://saucelabs.com/terms-of-service
  version: v1alpha1
  title: Hosted Test Executor
  contact:
    name: Sauce Labs Support
    url: https://saucelabs.com/support
    email: support@saucelabs.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: v1alpha1
paths:
  /hosted/image/runners:
    post:
      summary: Trigger a new hosted test-runner execution
      description: Trigger a new containerized hosted test-runner execution
      tags:
        - image
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RunnerSpec"
      responses:
        '201':
          description: Successful operation. Test-runner session created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Runner"
        '400':
          description: Invalid test-runner spec supplied
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
    get:
      summary: Get the hosted test-runners.
      tags:
        - image
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
        - in: query
          name: offset
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '201':
          description: Successful operation. List of runners.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/RunnerList"
  /hosted/image/runners/{id}:
    get:
      summary: Get the hosted test-runner details.
      tags:
        - image
      parameters:
        - name: id
          in: path
          description: Runner ID.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Test-runner details.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/RunnerDetails"
    delete:
      summary: Terminate a hosted test-runner being executed.
      tags:
        - image
      parameters:
        - name: id
          in: path
          description: Test-runner ID.
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Test-runner is terminated.
components:
  schemas:
    ContainerSpec:
      type: object
      description: Test-runner container specification.
      required:
        - name
      properties:
        name:
          type: string
          example: saucelabs/image:sha1
        auth:
          type: object
          required:
            - user
            - password
          properties:
            user:
              type: string
            token:
              type: string
    RunnerSpec:
      type: object
      description: Test-runner specification.
      required:
        - image
      properties:
        metadata:
          "$ref": "#/components/schemas/RunnerMetadata"
        container:
          "$ref": "#/components/schemas/ContainerSpec"
        entrypoint:
          type: string
          description: Command used to run tests.
          example: python -m pytest tests/integration
        env:
          type: array
          description: List of environment variables.
          items:
            "$ref": "#/components/schemas/EnvItem"
        files:
          type: array
          description: Test Runner container-mounted files.
          items:
            "$ref": "#/components/schemas/File"
        artifacts:
          type: array
          description: Test output files.
          items:
            type: string
          example:
            - /path/inside/container/file1.log
            - /path/inside/container/file2.log
    File:
      type: object
      description: Test Runner internal file.
      required:
        - path
        - data
      properties:
        path:
          type: string
          description: Test Runner configuration file mount path inside a container.
          example: /path/inside/container/config.json
        data:
          type: string
          description: Base64-encoded configuration file.
          example: base64string==
    EnvItem:
      type: object
      description: Environment variable item.
      required:
        - name
        - value
      properties:
        name:
          type: string
          description: Environment variable name.
          example: FOO
        value:
          description: Environment variable value.
          type: string
          example: bar
    RunnerMetadata:
      type: object
      description: Test-runner metadata, arbitrary key-value pairs.
      example:
        name: pytest - 123
      additionalProperties: true
    Runner:
      type: object
      description: Test-runner details.
      required:
        - id
        - status
        - image
        - creation_time
      properties:
        id:
          type: string
          description: Runner ID.
          example: 8e424261e0a54615ae227164bbd9baa0
        status:
          type: string
          description: Test-runner state.
          example: Created
        image:
          type: string
          description: the image
          example: image:1.2.3
        creation_time:
          type: integer
          format: int64
          description: Test-runner creation time.
          example: 1667143827
        termination_time:
          type: integer
          description: Test-runner execution termination time.
          format: int64
          example: 1667143867
        termination_reason:
          type: string
          description: a code describing why the test terminated
    RunnerList:
      type: object
      required:
        - content
      properties:
        content:
          type: array
          description: A List of test-runners.
          items:
            "$ref": "#/components/schemas/Runner"
    RunnerDetails:
      type: object
      allOf:
        - $ref: "#/components/schemas/Runner"
        - type: object
          properties:
              metadata:
                $ref: "#/components/schemas/RunnerMetadata"
    Error:
      type: object
      description: Generic error
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code.
          example: INVALID_INPUT
        message:
          type: string
          description: Error message.
          example: missing fields
