---
openapi: 3.0.3
info:
  description: |
    Sauce Labs Hosted Test Executor REST API.
  termsOfService: https://saucelabs.com/terms-of-service
  version: v1alpha1
  title: Hosted Test Executor
  contact:
    name: Sauce Labs Support
    url: https://saucelabs.com/support
    email: support@saucelabs.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: /v1alpha1
paths:
  /hosted/image/runners:
    post:
      summary: Trigger a new hosted test-runner execution
      description: Trigger a new containerized hosted test-runner execution
      tags:
        - image
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RunnerSpec"
      responses:
        '201':
          description: Successful operation. Test-runner session created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Runner"
        '400':
          description: Invalid test-runner spec supplied
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
    get:
      summary: Get the hosted test-runners.
      tags:
        - image
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
        - in: query
          name: offset
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Successful operation. List of runners.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/RunnerList"
  /hosted/image/runners/{id}:
    get:
      summary: Get the hosted test-runner details.
      tags:
        - image
      parameters:
        - name: id
          in: path
          description: Runner ID.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Test-runner details.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/RunnerDetails"
    delete:
      summary: Terminate a hosted test-runner being executed.
      tags:
        - image
      parameters:
        - name: id
          in: path
          description: Test-runner ID.
          required: true
          schema:
            type: string
        - name: force
          in: query
          description: forces deletion
          schema:
            type: boolean
            default: false
      responses:
        '204':
          description: Test-runner is terminated.
  /hosted/image/runners/{id}/status:
    get:
      summary: Get the hosted test-runner status.
      tags:
        - image
      parameters:
        - name: id
          in: path
          description: Runner ID.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Test-runner status.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/RunnerStatus"
  /hosted/image/runners/{id}/spec:
    get:
      summary: Get the hosted test-runner spec.
      tags:
        - image
      parameters:
        - name: id
          in: path
          description: Runner ID.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Test-runner spec.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RunnerDetails"
  /hosted/image/runners/{id}/logs/url:
    get:
      summary: Get url to fetch test-runner's logs.
      tags:
        - image
        - artifacts
      parameters:
        - name: id
          in: path
          description: Runner ID.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: URL to fetch test-runner's logs.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RunnerLogsUrl"
  /hosted/image/runners/{id}/artifacts/url:
    get:
      summary: Get url to fetch test-runner's artifacts.
      tags:
        - image
        - artifacts
      parameters:
        - name: id
          in: path
          description: Runner ID.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: URL to fetch test-runner's artifacts.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RunnerArtifactsUrl"
components:
  schemas:
    ContainerSpec:
      type: object
      description: Test-runner container specification.
      required:
        - name
      properties:
        name:
          type: string
          minLength: 3
          example: saucelabs/image:sha1
        auth:
         $ref: "#/components/schemas/Auth"
    Tunnel:
      type: object
      description: Test-runner tunnel configuration.
      properties:
        name:
          type: string
          example: my_tunnel
        owner:
          type: string
          example: my_co
    Auth:
      type: object
      required:
        - user
        - token
      properties:
        user:
          type: string
          minLength: 2
        token:
          type: string
          minLength: 2
    RunnerSpec:
      type: object
      description: Test-runner specification.
      required:
        - container
      properties:
        metadata:
          "$ref": "#/components/schemas/RunnerMetadata"
        container:
          "$ref": "#/components/schemas/ContainerSpec"
        entrypoint:
          type: string
          description: Command used to run tests.
          example: python -m pytest tests/integration
        workload_type:
          type: string
          enum:
            - webdriver
            - other
          description: Workload type.
          example: webdriver
        env:
          type: array
          description: List of environment variables.
          items:
            "$ref": "#/components/schemas/EnvVar"
        files:
          type: array
          description: Test Runner container-mounted files.
          items:
            "$ref": "#/components/schemas/File"
        tunnel:
          "$ref": "#/components/schemas/Tunnel"
        artifacts:
          type: array
          maxItems: 10
          description: Test output files.
          items:
            type: string
          example:
            - /workdir/dir1/file.txt
            - /workdir/dir2/*/*.txt
    File:
      type: object
      description: Test Runner internal file.
      required:
        - path
        - data
      properties:
        path:
          type: string
          description: Test Runner configuration file mount path inside a container.
          example: /path/inside/container/config.json
        data:
          type: string
          description: Base64-encoded configuration file.
          example: base64string==
    EnvVar:
      type: object
      description: Environment variable.
      required:
        - name
        - value
      properties:
        name:
          type: string
          pattern: '^[a-zA-Z_][a-zA-Z0-9_].+'
          description: Environment variable name.
          example: FOO
        value:
          description: Environment variable value.
          type: string
          example: bar
    RunnerMetadata:
      type: object
      description: Test-runner metadata, arbitrary key-value pairs.
      example:
        name: pytest - 123
      additionalProperties: true
    Runner:
      type: object
      description: Test-runner details.
      required:
        - id
        - status
        - image
        - creation_time
        - assets_uploaded
      properties:
        id:
          type: string
          description: Runner ID.
          example: 8e424261e0a54615ae227164bbd9baa0
        status:
          type: string
          description: Test-runner state.
          example: Created
        image:
          type: string
          description: the image
          example: image:1.2.3
        creation_time:
          type: integer
          format: int64
          description: Test-runner creation time.
          example: 1667143827
        termination_time:
          type: integer
          description: Test-runner execution termination time.
          format: int64
          example: 1667143867
        termination_reason:
          type: string
          description: a code describing why the test terminated
        assets_uploaded:
          type: boolean
          description: a flag indicating assets upload status
    RunnerList:
      type: object
      required:
        - content
      properties:
        content:
          type: array
          description: A List of test-runners.
          items:
            "$ref": "#/components/schemas/Runner"
    RunnerStatus:
      type: object
      required:
        - id
        - status
        - creation_time
        - assets_uploaded
      properties:
        id:
          type: string
        status:
          type: string
        creation_time:
          type: integer
          format: int64
        termination_time:
          type: integer
          format: int64
        termination_reason:
          type: string
        assets_uploaded:
          type: boolean
    RunnerDetails:
      type: object
      allOf:
        - $ref: "#/components/schemas/Runner"
        - type: object
          properties:
              metadata:
                $ref: "#/components/schemas/RunnerMetadata"
    RunnerLogsUrl:
      type: object
      required:
        - url
      properties:
        url:
          type: string
    RunnerArtifactsUrl:
      type: object
      required:
        - url
      properties:
        url:
          type: string
    Error:
      type: object
      description: Generic error
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code.
          example: INVALID_INPUT
        message:
          type: string
          description: Error message.
          example: missing fields
