---
name: Ensure generated files are up-to-date
on: [push, pull_request]  # yamllint disable-line rule:truthy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run `make generate`
        run: make generate

      - name: Check for no untracked files
        run: git status && git diff-index --quiet HEAD --
