---
name: Lint project
on: [push, pull_request]  # yamllint disable-line rule:truthy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Make sure this matches the version we've got in our `Makefile`
          version: v1.59.1
